version: 2.1
commands:
  login_on_gcp:
    description: Login to Google Cloud SDK
    parameters:
      gcloud_key:
        type: string
      project:
        type: string
    steps:
      - run: |
          echo << parameters.gcloud_key >> | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project << parameters.project >>

  upload_image_on_gcp:
    description: Upload Docker image on GCP
    parameters:
      image:
        type: string
    steps:
      - run: gcloud builds submit --tag gcr.io/<< parameters.image >>

  deploy_on_gcp:
    description: Deploy Docker
    parameters:
      image:
        type: string
      env:
        type: string
    steps:
      - run: gcloud beta run deploy --image gcr.io/<< parameters.image >> --platform managed --region europe-west1 --allow-unauthenticated --set-env-vars ENV=<< parameters.env >>

  delete_container_image:
    description: Delete container image
    parameters:
      image:
        type: string
    steps:
      - run: gcloud container images delete gcr.io/<< parameters.image >> -q --force-delete-tags

jobs:
  build_deploy_peer:
    working_directory: ~/phonepad.js/server
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/phonepad.js
      - login_on_gcp:
          gcloud_key: $GCLOUD_SERVICE_KEY_PROD
          project: api-project-725491021247
      - upload_image_on_gcp:
          image: api-project-725491021247/peer2peer
      - deploy_on_gcp:
          image: api-project-725491021247/peer2peer
          env: production
      - delete_container_image:
          image: api-project-725491021247/peer2peer
  build_deploy_pad:
    working_directory: ~/phonepad.js/phonepad
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/phonepad.js
      - login_on_gcp:
          gcloud_key: $GCLOUD_SERVICE_KEY_PROD
          project: api-project-725491021247
      - upload_image_on_gcp:
          image: api-project-725491021247/phonepad
      - deploy_on_gcp:
          image: api-project-725491021247/phonepad
          env: production
      - delete_container_image:
          image: api-project-725491021247/phonepad

workflows:
  build_deploy:
    jobs:
      - build_deploy_peer:
          filters:
            branches:
              only:
                - master
      - build_deploy_pad:
          filters:
            branches:
              only:
                - master
